/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ComponentPanel: typeof import('./src/components/DesignerView/Panels/ComponentPanel/ComponentPanel.vue')['default']
    DataSourcePanel: typeof import('./src/components/DesignerView/Panels/DataSourcePanel.vue')['default']
    DesignCanvas: typeof import('./src/components/DesignerView/DesignCanvas/DesignCanvas.vue')['default']
    DragFormNode: typeof import('./src/components/DesignerView/Panels/ComponentPanel/child/DragFormNode.vue')['default']
    DragWrapper: typeof import('./src/components/CommonComponents/DragWrapper.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    LayoutItem: typeof import('./src/components/CommonComponents/LayoutItem.vue')['default']
    MountDatePicker: typeof import('./src/components/MountComponents/MountDatePicker.vue')['default']
    MountForm: typeof import('./src/components/MountComponents/MountForm.vue')['default']
    MountInput: typeof import('./src/components/MountComponents/MountInput.vue')['default']
    MountItemLayout: typeof import('./src/components/MountComponents/MountItemLayout.vue')['default']
    MountLayout: typeof import('./src/components/MountComponents/MountLayout.vue')['default']
    OutlineTreePanel: typeof import('./src/components/DesignerView/Panels/OutlineTreePanel.vue')['default']
    PanelTabs: typeof import('./src/components/DesignerView/PanelTabs.vue')['default']
    PlaceWrapper: typeof import('./src/components/CommonComponents/PlaceWrapper.vue')['default']
    PropertyPanel: typeof import('./src/components/DesignerView/Panels/PropertyPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RyButton: typeof import('./src/components/CommonComponents/RyButton.vue')['default']
    Toolbar: typeof import('./src/components/DesignerView/Toolbar.vue')['default']
    Topbar: typeof import('./src/components/DesignerView/Topbar.vue')['default']
  }
}
